
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC7xBJwmmUs66XnClr-X4oOzqxamx3ef0',
    appId: '1:1076958773491:web:9c1ef55df29aa8b2743786',
    messagingSenderId: '1076958773491',
    projectId: 'cpsc4250-game',
    authDomain: 'cpsc4250-game.firebaseapp.com',
    storageBucket: 'cpsc4250-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0sjZo2koblCYLTQ0lS96zEg3S5X3XFmk',
    appId: '1:1076958773491:android:42d7d4105d05fa9c743786',
    messagingSenderId: '1076958773491',
    projectId: 'cpsc4250-game',
    storageBucket: 'cpsc4250-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiegTvMdBK935DK941n6XXRU1XPccZwas',
    appId: '1:1076958773491:ios:77119662f33a88b7743786',
    messagingSenderId: '1076958773491',
    projectId: 'cpsc4250-game',
    storageBucket: 'cpsc4250-game.appspot.com',
    iosClientId: '1076958773491-s3cbqf9pcqsqqrtmfnlc9gctv6jn0a98.apps.googleusercontent.com',
    iosBundleId: 'com.example.chimpGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiegTvMdBK935DK941n6XXRU1XPccZwas',
    appId: '1:1076958773491:ios:77119662f33a88b7743786',
    messagingSenderId: '1076958773491',
    projectId: 'cpsc4250-game',
    storageBucket: 'cpsc4250-game.appspot.com',
    iosClientId: '1076958773491-s3cbqf9pcqsqqrtmfnlc9gctv6jn0a98.apps.googleusercontent.com',
    iosBundleId: 'com.example.chimpGame',
  );
}
